[package]
name = "paracode-macros"
version = "3.0.0"
authors = ["DaRubyMiner360"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
paracode = {path = "../paracode"}
syn = "1.0.103"
quote = "1.0.21"
