# Configuration For The Shell
[shell]
userColor = "white"
userStyle = "none"
consoleColor = "white"
consoleStyle = "none"
pointerColor = "green"
pointerStyle = "none"
errorColor = "red"
errorStyle = "none"

# Configuration For ParaCode
[lang]
packagePath = "Packages/"