[package]
name = "paracode-repl"
version = "3.0.0"
authors = ["DaRubyMiner360"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paracode = {path = "../paracode"}
