[package]
name = "paracode-repl"
version = "3.0.0"
authors = ["DaRubyMiner360"]
edition = "2021"

[dependencies]
paracode = {path = "../paracode"}
signal-hook = "0.3.14"
quit = "1.1.4"
rustyline = "10.0.0"
